const constants = {
  COLUMN_TOP_Y: 50,
  COLUMN_WIDTH: 150,
  ROW_HEIGHT: 150,
  METHOD_NAME_COLUMN_WIDTH: 180,
  DASH_WIDTH: 4,
  DASH_HEIGHT: 10,
  DASH_VERTICAL_MARGIN: 12,
  METHOD_RADIUS: 30,
  TITLE_FRAME_VERTICAL_PADDING: 2,
  TITLE_FRAME_HORIZONTAL_PADDING: 20,
  TITLE_FRAME_STROKE_WIDTH: 3,
  TITLE_FONT_SIZE: 14,
  METHOD_LEGEND_FONT_SIZE: 18,
  METHOD_LEGEND_LEFT_PADDING: 20,
  VERTICAL_MARGIN_FROM_TOP: 20,
}

module.exports = constants;
