const constants = {
  COLUMN_TOP_Y: 50,
  COLUMN_WIDTH: 50,
  ROW_HEIGHT: 50,
  METHOD_NAME_COLUMN_WIDTH: 50,
  DASH_WIDTH: 6,
  DASH_HEIGHT: 12,
  DASH_VERTICAL_MARGIN: 10,
  METHOD_RADIUS: 30,
}

module.exports = constants;
