const BAR_WIDTH = 30;
const BAR_PADDING = 2;
const BAR_LAYER_LEFT_MARGIN = 40;
const Y_AXIS_WIDTH = 100;
const Y_AXIS_LINE_WIDTH = 6;
const LABEL_HEIGHT = 40;
const BAR_BOTTOM_MARGIN = LABEL_HEIGHT + 5;
const PADDING = 250;
const EMPTY_SPACE_TOP_PERCENTAGE = 10;

module.exports = {
  Y_AXIS_WIDTH,
  BAR_BOTTOM_MARGIN,
  PADDING,
  EMPTY_SPACE_TOP_PERCENTAGE,
  BAR_LAYER_LEFT_MARGIN,
  BAR_WIDTH,
  BAR_PADDING,
};
